### ISSUE TITLE
Plugin apply an incompatible color scheme on the editor specifically on the Gerry Sotrm Theme

### ISSUE THREAD

**Issue by wissemgrari** [gerryhjs/gerry-themes#11]

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8  
This is an issue caused by IDE Setting Sync, please check:
https://github.com/gerryhjs/gerry-themes/issues/8
https://youtrack.jetbrains.com/issue/IDEA-327446
https://youtrack.jetbrains.com/issue/IDEA-325237

Workaround: Check the Settings | Editor | Color Scheme window and select the color scheme corresponding to the theme you use.
