### ISSUE TITLE
Latest update broke Gerry Dracula

### ISSUE THREAD

**Issue by akkadaya** [gerryhjs/gerry-themes#12]
I've updated the plugin to 2023.1.63 on IntelliJ IDEA 2023.2.1 then this happened! I'm using Gerry Dracula theme

<img width="1676" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/1834445/ffcc4e7a-632c-4ec9-8ec9-b661d3c51e2d">

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8  

This is an issue caused by IDE Setting Sync, please check:
https://github.com/gerryhjs/gerry-themes/issues/8
https://youtrack.jetbrains.com/issue/IDEA-327446
https://youtrack.jetbrains.com/issue/IDEA-325237

Workaround: Check the Settings | Editor | Color Scheme window and select the color scheme corresponding to the theme you use.

**Comment by gerryhjs** [comment]
PS: Last update add this workaround description since it is reported serval times, you could find same workaround in plugin description. I also contact with Jetbrains internally about this issue.
