### ISSUE TITLE
Gerry Violet

### ISSUE THREAD

**Issue by StevoIsBetter** [gerryhjs/gerry-themes#13]
I use the Gerry Violet in Intellij and after the update, I got flashbanged with a white background. All of the other ones work fine it's just that the theme specifically has a white background.

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8  

This is an issue caused by IDE Setting Sync, please check:
https://github.com/gerryhjs/gerry-themes/issues/8
https://youtrack.jetbrains.com/issue/IDEA-327446
https://youtrack.jetbrains.com/issue/IDEA-325237

Workaround: Check the Settings | Editor | Color Scheme window and select the color scheme corresponding to the theme you use.
