### ISSUE TITLE
Icons are not aligned on MacOS.

### ISSUE THREAD

**Issue by xyzpinecone** [gerryhjs/gerry-themes#15]
[](url)
<img width="295" alt="截屏2023-10-19 23 25 23" src="https://github.com/gerryhjs/gerry-themes/assets/12005965/8265c9f9-115f-4ae4-8c11-6264a62175f6">

The Setting Icon is not aligned with other icons in the right.

Idea Version: 2023.2.3
MacOS Version: MacOS Senoma

Other third-party themes has same issus. Not knowing wether this was a compatibility issue with lates idea version. Official Thems has no such problem.

**Comment by gerryhjs** [comment]
Yes. This is a compatibility issue with new UI. 
I have found the workaround and it will fix in the next release.
Please install EAP version here and check if this issue is solved:
https://plugins.jetbrains.com/plugin/18922-gerry-themes/versions/eap
https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/eap

**Comment by xyzpinecone** [comment]
solved! 2023.1.72 EAP version works perfectly fine now.
Thank you.
