### ISSUE TITLE
Database view not styled with Gerry Dark theme

### ISSUE THREAD

**Issue by DanielPower** [gerryhjs/gerry-themes#18]
Gerry Theme Version: 2023.1.80
Webstorm Version: 2023.2.5
Database Tools Plugin Version: 232.10227.9

This issue only occurs with "Gerry Dark". Other color schemes render correctly.

![image](https://github.com/gerryhjs/gerry-themes/assets/12166320/e856f674-d37b-4e69-bed5-d685e769e878)
![image](https://github.com/gerryhjs/gerry-themes/assets/12166320/b2be2498-ebe0-440e-9e8a-fd5844beef2a)
![image](https://github.com/gerryhjs/gerry-themes/assets/12166320/5b095e87-65ca-4cdb-ac19-ee083ead1d7c)
![image](https://github.com/gerryhjs/gerry-themes/assets/12166320/52414137-ba8c-4aba-bb2f-240884311c7c)

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8  

Workaround:
This is an issue caused by IDE Setting Sync, it will apply a wrong color scheme in some cases([IDEA-325237](https://youtrack.jetbrains.com/issue/IDEA-325237)).
Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme as the workaround.
