### ISSUE TITLE
White code editor

### ISSUE THREAD

**Issue by angusaustralia** [gerryhjs/gerry-themes#19]
Hi, 

I often get this after an upgrade but usually a quit and re-launch of PHPstorm fixes it.  Not with his latest revision 2023.1.80

The white background doesn't go dark

<img width="1469" alt="Screenshot 2023-11-16 at 3 34 19 pm" src="https://github.com/gerryhjs/gerry-themes/assets/71737626/a6857d08-3491-459e-b61f-c2fe4d3afb18">

I am a paid subscriber.

TIA
Dr Gerard Hammond

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8  

Workaround:
This is an issue caused by IDE Setting Sync, it will apply a wrong color scheme in some cases([IDEA-325237](https://youtrack.jetbrains.com/issue/IDEA-325237)).
Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme as the workaround.
