### ISSUE TITLE
white Background with "Gerry Dark/Darcula" IntelliJ

### ISSUE THREAD

**Issue by Jarno0110** [gerryhjs/gerry-themes#24]
Hello, the Gerry Dark and Gerry Darcula themes have recently been given a white background in the code field (see images). I loved Gerry Dark but now it is no longer usable. 
Greetings Jarno
<img width="1702" alt="Gerry Darcula" src="https://github.com/gerryhjs/gerry-themes/assets/99245448/704b685a-927d-4683-8ee9-06a8b0b2d108">
Gerry Darcula
<img width="1702" alt="Gerry Dark" src="https://github.com/gerryhjs/gerry-themes/assets/99245448/b8fa6732-e25e-4494-b697-687f3c21aac4">
Gerry Dark

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8

Workaround:
This is an issue caused by IDE Setting Sync, it will apply a wrong color scheme in some cases([IDEA-325237](https://youtrack.jetbrains.com/issue/IDEA-325237)).
Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme as the workaround.

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8

This is an issue caused by IDE, it may apply a incompatible color scheme in some cases([IDEA-325237](https://youtrack.jetbrains.com/issue/IDEA-325237)).
Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme. (Switch to Gerry Dark/Darcula)

**Comment by Jarno0110** [comment]
Thanks, that worked
