### ISSUE TITLE
黑色主题下页面显示为白色

### ISSUE THREAD

**Issue by OrionLi** [gerryhjs/gerry-themes#28]
在Gerry Dark、Gerry Oceanic主题下，代码页面呈白色
![image](https://github.com/gerryhjs/gerry-themes/assets/110345045/c2f51835-f21c-4df7-9a87-326cfdff1ada)

**Comment by gerryhjs** [comment]
Duplicate to #8
This is an issue caused by IDE, it may apply an incompatible color scheme in some cases(IDEA-325237). Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme. For example: If you are using "Gerry Darcula" or "Legacy Gerry Darcula", then switch color scheme to "Gerry Darcula".

这是 IDE 引起的问题，在某些情况下它可能会应用不兼容的配色方案（IDEA-325237）。请检查 "设置"|"编辑器"|"配色方案 "窗口并选择相应的配色方案。例如 如果您使用的是 "Gerry Darcula "或 "Legacy Gerry Darcula"，请将配色方案切换为 "Gerry Darcula"。

**Comment by gerryhjs** [comment]
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/ba746698-efeb-45c8-8090-ae6867b4f1e2)
