### ISSUE TITLE
Folder icon not displayed when using light mode in folder pickers

### ISSUE THREAD

**Issue by Yoshlix** [gerryhjs/gerry-themes#31]
![grafik](https://github.com/gerryhjs/gerry-themes/assets/75274054/8a28b9bf-60a6-4775-9972-4eaaa40d3cfe)

Only when you select the entry, a light folder icon is displayed. This only happens when using the light theme and occurs on all folder pickers.

Using Android Studio Iguana | 2023.2.1 and Gerry Themes 2024.1.0315

**Comment by gerryhjs** [comment]
This is likely an issue duplicate to https://github.com/gerryhjs/gerry-themes/issues/14.
which is caused by IDE: https://youtrack.jetbrains.com/issue/IDEA-323076/Incorrect-color-of-Icon-More-Actions-in-Run-Configuration-widget

Could you try switch to the build in themes "Intelij Light" and check issue if issue is still exsist.

**Comment by gerryhjs** [comment]
Could not reproduce for me.
I am using Android Studio 2023.2.1 and Gerry Themes 2024.1.0315. Please also try restart Android Studio after switch themes.

**Comment by Yoshlix** [comment]
I switched the themes and now it shows correctly. Seems like an IDE bug.
