### ISSUE TITLE
Latest updates made the dark themes white

### ISSUE THREAD

**Issue by codeananda** [gerryhjs/gerry-themes#32]
It was all working perfectly but the most recent updates (the first being 10th March) made the dark themes white

Gerry Dark
<img width="1280" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/51246969/2ca4992c-1166-426c-9517-0c30e63d489d">

Legacy Gerry Dark
<img width="1280" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/51246969/7cb695a6-cc0c-4d66-a39c-1627131e9e1c">

Others work ok, e.g. Gerry Oceanic
<img width="1280" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/51246969/0054e733-c556-4a75-b7ec-eb571d45307b">

But my favourite was Gerry Dark!

What's going on?

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8
This is an issue caused by IDE, it may apply an incompatible color scheme in some cases(IDEA-325237). Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme. For example: If you are using "Gerry Darcula" or "Legacy Gerry Darcula", then switch color scheme to "Gerry Darcula".

PS: You could also find this workaround in plugin description .

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8
This is an issue caused by IDE, it may apply an incompatible color scheme in some cases ([IDEA-325237](https://youtrack.jetbrains.com/issue/IDEA-325237)).
Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme, the issue should be solved.
For example: If you are using "Gerry Darcula" or "Legacy Gerry Darcula", then switch color scheme to "Gerry Darcula".

**Comment by codeananda** [comment]
Thanks that works :)
