### ISSUE TITLE
Theme background color not working in Jupyter Notebook cells

### ISSUE THREAD

**Issue by LouisLecouturier** [gerryhjs/gerry-themes#39]
The background of notebook cells (.ipynb files) remains the same as the default theme

![image](https://github.com/user-attachments/assets/a13dc4c7-cab4-4b68-a7b3-624546b5e3ba)

**Comment by LouisLecouturier** [comment]
Same goes for the new terminal UI

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/1ab4efdc-f1e7-4b84-97e1-28a039ed7a10">

**Comment by gerryhjs** [comment]
The new terminal UI is still in EAP, maybe check with check & improve after release. 
As for notebook I will check it later (downloading Pycharm..)

**Comment by gerryhjs** [comment]
Check the new terminal UI with internal mode, seems no related attribute could customized in current IDE version.
For notebook background, I have found the related attribute. I change the color to same background color looks a bit strange.
![image](https://github.com/user-attachments/assets/02f40a0e-f4af-4ef9-8877-9b78a98f9595)

**Comment by gerryhjs** [comment]
You could also modified the color mannually by File | Settings | Editor | Color Scheme | Notebooks | Code Cell Background
Though it could be modified, the border is still default background color. 
(I also found some refer issue on youtrack, seems issue is caused by IDE side. )
![image](https://github.com/user-attachments/assets/fd65fa8d-346f-436c-adc5-5b1923a70313)
