### ISSUE TITLE
Legacy theme support confirmation

### ISSUE THREAD

**Issue by Destaq** [gerryhjs/gerry-themes#7]
Hi Gerry,

Thanks for such an awesome set of themes! I just want to quickly run one check past you. The plug-in has a few (six) 'Legacy' themes that I regularly use over the existing ones. However, the word legacy suggests that they may, eventually, be discontinued.

Will these themes be always updated along with the other ones, or should I try to switch to something else?

**Comment by gerryhjs** [comment]
**No worried, Legacy themes are still well maintained same as normal themes and won't be deprecated. It is a part of plugin.** 
Gerry Themes (Pro) has swicthed themes style to project browser and editor panel to have same background color since early version, but I have recevied feedback some user still prefer different so I keep them stay as "leagcy style". Also I add some new legacy themes after that, such as Legacy Gerry Violet and Legacy Gerry Light.

**Comment by gerryhjs** [comment]
No worried, Legacy themes are still well maintained same as normal themes and won't be deprecated. It is just a variation.
Gerry Themes (Pro) has swicthed themes style to project browser and editor panel to have same background color since early version, but I have recevied feedback some user still prefer different so I keep them stay as "leagcy style". Also I add some new legacy themes after that, such as Legacy Gerry Violet and Legacy Gerry Light.

**Comment by Destaq** [comment]
That's great news, thanks for letting us know.
